'use client'

import { usePathname } from 'next/navigation'
import mtimes from '@/data/doc-mtimes.json'

// Visible "Last updated" line under doc page titles. Date comes from
// the per-route map generated by utils/generate-doc-mtimes.mjs at
// build time (git log of the source page file). This is the freshness
// signal Google's December 2025 core update started rewarding —
// winners averaged 393 days since last update vs. losers' 500 days.
//
// Returns the ISO timestamp string and a formatted human-readable
// string. The companion `<DocStructuredData lastUpdated={...} />`
// uses the ISO form for schema.org dateModified.
export function getLastUpdated(pathname) {
  if (!pathname) return null
  const iso = mtimes[pathname]
  if (!iso) return null
  return iso
}

export function LastUpdatedByline() {
  const pathname = usePathname()
  const iso = getLastUpdated(pathname)
  if (!iso) return null

  const formatted = new Date(iso).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  return (
    <p className="mt-2 text-xs text-slate-500">
      Last updated <time dateTime={iso}>{formatted}</time>
    </p>
  )
}
